portfolio/about_me/urls.py
from django.urls import path

from . import views

app_name = 'about_me'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact')
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path('', include('about_me.urls')),
    path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('project/<int:pk>/', views.ProjectView.as_view(), name='project-detail'),
    path('tag/<int:pk>/', views.TagView.as_view(), name='tag-detail'),
]

portfolio/about_me/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class WorkExperience(models.Model):
    title = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return self.title + ' at ' + self.company

class Skill(models.Model):
    name = models.CharField(max_length=100)
    proficiency = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    
    def __str__(self):
        return self.name

portfolio/projects/models.py
from django.db import models
from django.contrib import admin

class Project(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('Tag', through='ProjectTag')
    image = models.ImageField(upload_to='projects/', blank=True, null=True)

    def __str__(self):
        return self.title

class Tag(models.Model):
    name = models.CharField(max_length=100)
    projects = models.ManyToManyField('Project', through='ProjectTag')

    def __str__(self):
        return self.name

class ProjectTag(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.project.title} tagged with {self.tag.name}'


# --- admin config ---

class TagInline(admin.TabularInline):
    model = Project.tags.through
    extra = 0

class ProjectAdmin(admin.ModelAdmin):
    inlines = (TagInline,)

portfolio/about_me/views.py
from django.views import generic

from .models import WorkExperience, Skill

class IndexView(generic.base.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        work_experiences = WorkExperience.objects.order_by('-start_date')
        context['title'] = 'About Me'
        context['work_experiences'] = work_experiences
        context['skills'] = Skill.objects.order_by('-proficiency')
        return context

class ContactView(generic.base.TemplateView):
    template_name = 'contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Contact'
        return context

portfolio/projects/views.py
from django.views import generic
from django.db.models import Q

from .models import Project, Tag

class IndexView(generic.base.TemplateView):
    template_name = 'projects/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Projects'
        context['project_list'] = Project.objects.all()
        context['tag_list'] = Tag.objects.all()
        return context

class ProjectView(generic.DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['project'].title
        return context

class TagView(generic.DetailView):
    model = Tag

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['tag'].name
        return context

class SearchView(generic.base.TemplateView):
    template_name = 'projects/search.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Search'
        context['query'] = self.request.GET.get('query')
        if context['query']:
            results = Project.objects.complex_filter(
                Q(title__icontains=context['query']) |
                Q(content__icontains=context['query']) |
                Q(tags__name__icontains=context['query'])
            )
            context['project_list'] = results
        else:
            context['project_list'] = Project.objects.all()
        return context

portfolio/about_me/templates/contact.html
{% extends "base.html" %}

{% block content %}
<h1>Contact</h1>
<hr>
<p>
    <b>Address</b><br>
    Jelle Schutter<br>
    Etzelmatt 4<br>
    5430 Wettingen
</p>
<p>
    <b>Email</b><br>
    <a href="mailto:jelle@schutter.xyz">jelle@schutter.xyz</a>
</p>
<p>
    <b>Phone</b><br>
    <a href="tel:+41766752239">+41 76 675 22 39</a>
</p>
{% endblock content %}

portfolio/about_me/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Jelle Schutter</h1>
<hr>
<div class="socials">
    <a class="social" href="https://github.com/jelleschutter/">
        <div>
            <svg class="social-icon" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512">
                <path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path>
            </svg>jelleschutter
        </div>
    </a>
    <a class="social" href="https://www.linkedin.com/in/jelleschutter/">
        <div>
            <svg class="social-icon" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="currentColor" d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"></path>
            </svg>jelleschutter
        </div>
    </a>
    <a class="social" href="mailto:jelle@schutter.xyz">
        <div>
            <svg class="social-icon" aria-hidden="true" focusable="false" data-prefix="far" data-icon="envelope" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path fill="currentColor" d="M464 64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm0 48v40.805c-22.422 18.259-58.168 46.651-134.587 106.49-16.841 13.247-50.201 45.072-73.413 44.701-23.208.375-56.579-31.459-73.413-44.701C106.18 199.465 70.425 171.067 48 152.805V112h416zM48 400V214.398c22.914 18.251 55.409 43.862 104.938 82.646 21.857 17.205 60.134 55.186 103.062 54.955 42.717.231 80.509-37.199 103.053-54.947 49.528-38.783 82.032-64.401 104.947-82.653V400H48z"></path>
            </svg>jelle@schutter.xyz
        </div>
    </a>
</div>
<h2>About Me</h2>
<hr>
<p>Hi there! Welcome to my website. My name is Jelle and I study Data Science at FHNW. This website was created as a part of the "Web Technologies" course.</p>

<h2>Work Experiences</h2>
<hr>
{% for work_experience in work_experiences %}
    <div class="work-experiences--wrapper">
        <div class="work-experiences--item work-experiences--{% cycle 'left' 'right' %}">
            <div class="work-experiences--content">
                {% ifchanged work_experience.company %}
                    <h3 class="work-experiences--company">{{ work_experience.company }}</h3>
                {% endifchanged %}
                <div class="work-experiences--position">
                    <h4>{{ work_experience.title }}</h4>
                    <p class="work-experiences--date">{{ work_experience.start_date|date:"F Y" }} - {{ work_experience.end_date|date:"F Y"|default:"Now" }}</p>
                    <p>{{ work_experience.description }}</p>
                    <div class="work-experiences--tick"></div>
                </div>
            </div>
        </div>
        <div class="work-experiences--filler work-experiences--{% cycle 'right' 'left' %}"></div>
    </div>
{% endfor %}
<script>
    const workExperienceItems = document.querySelectorAll('.work-experiences--item');
    const intersectionObserver = new IntersectionObserver((entries) => {
        entries.forEach((entry) => {
            if (entry.isIntersecting) {
                entry.target.classList.add('work-experiences--item--visible');
            } else {
                entry.target.classList.remove('work-experiences--item--visible');
            }
        });
    }, {
        threshold: 0.3
    });
    workExperienceItems.forEach((item) => {
        intersectionObserver.observe(item);
    });
</script>
{% if skills %}
<h2>Skills</h2>
<hr>
<div class="skills--wrapper">
    {% for skill in skills %}
        <div class="skills--item-name">{{ skill.name }}</div>
        <div class="skills--item-bar" data-proficiency="{{ skill.proficiency }}"></div>
    {% endfor %}
</div>
<script>
    const skillItems = document.querySelectorAll('.skills--item-bar');
    const skillIntersectionObserver = new IntersectionObserver((entries) => {
        entries.forEach((entry) => {
            if (entry.isIntersecting) {
                entry.target.style.width = `${entry.target.dataset.proficiency}%`;
                entry.target.classList.add('skills--item-bar--visible');
            } else {
                entry.target.style.width = '';
                entry.target.classList.remove('skills--item-bar--visible');
            }
        });
    }, {
        threshold: 0.5,
    });
    skillItems.forEach((item) => {
        skillIntersectionObserver.observe(item);
    });
</script>
{% endif %}
{% endblock content %}

portfolio/portfolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} | Jelle Schutter</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
    <nav>
        <a href="{% url 'about_me:index' %}">About Me</a>
        <a href="{% url 'projects:index' %}">Projects</a>
        <a href="{% url 'about_me:contact' %}">Contact</a>
    </nav>
    <main>
        {% block content %}
        <h1>Not Found</h1>
        {% endblock content %}
    </main>
    <footer>
        <hr>
        <p>&copy; 2024 Jelle Schutter</p>
    </footer>
</body>
</html>

portfolio/projects/templates/projects/index.html
{% extends "base.html" %}

{% block content %}
<h2>Filter</h2>
<hr>
{% if tag_list %}
    <div class="tag-filter">
        {% for tag in tag_list %}
            <a href="{% url 'projects:tag-detail' tag.id %}">{{ tag.name }}</a>{% if not forloop.last %} | {% endif %}
        {% endfor %}
    </div>
    <br/>
{% endif %}
<form method="get" action="{% url 'projects:search' %}">
    <div class="form-group">
        <input type="text" name="query" class="form-control" value="{{ query }}" placeholder="Search for projects...">
        <button type="submit">Search</button>
    </div>
</form>

{% if project_list %}
    <h1>Projects</h1>
    <hr>
    <div class="project-list--wrapper">
        {% for project in project_list %}
            <a class="project-list--item" href="{% url 'projects:project-detail' project.id %}">
                <img class="project-list--image" src="{{ project.image.url }}" alt="{{ project.title }}">
                <p class="project-list--title">{{ project.title }}</p>
            </a>
        {% endfor %}
    </div>
{% else %}
    <p>No projects are available.</p>
{% endif %}
{% endblock content %}

portfolio/projects/templates/projects/project_detail.html
{% extends "base.html" %}

{% block extra_head %}
<meta property="og:title" content="{{ project.title }}">
<meta property="og:image" content="{{ project.image.url }}">
{% endblock extra_head %}

{% block content %}
<img class="project-image" src="{{ project.image.url }}" alt="{{ project.title }}">
<h1>{{ project.title }}</h1>
<hr>
{{ project.content }}
{% endblock content %}

portfolio/projects/templates/projects/search.html
{% extends "base.html" %}

{% block content %}
    <h2>Search</h2>
    <hr>
    <form method="get">
        <div class="form-group">
            <input type="text" name="query" class="form-control" value="{{ query }}">
            <button type="submit">Search</button>
        </div>
    </form>
    <h1>Results for &#171;{{ query }}&#187;</h1>
    <hr>
    {% if project_list %}
    <div class="project-list--wrapper">
        {% for project in project_list %}
            <a class="project-list--item" href="{% url 'projects:project-detail' project.id %}">
                <img class="project-list--image" src="{{ project.image.url }}" alt="{{ project.title }}">
                <p class="project-list--title">{{ project.title }}</p>
            </a>
        {% endfor %}
    </div>
    {% else %}
        <p class="text-center">No results found.</p>
    {% endif %}
{% endblock content %}

portfolio/projects/templates/projects/tag_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Projects with &#171;{{ tag.name }}&#187; Tag</h1>
<hr>

{% if tag.project_set.all %}
    <div class="project-list--wrapper">
        {% for project in tag.project_set.all %}
            <a class="project-list--item" href="{% url 'projects:project-detail' project.id %}">
                <img class="project-list--image" src="{{ project.image.url }}" alt="{{ project.title }}">
                <p class="project-list--title">{{ project.title }}</p>
            </a>
        {% endfor %}
    </div>
{% else %}
    <p>This tag has not yet been used. Try again later.</p>
{% endif %}
{% endblock content %}